services:
  web:
    build:
      context: .
    env_file: .env
    environment:
      - DB_CONNECTION=postgresql://postgres:password@db:5432/postgres
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./data:/docker-entrypoint-initdb.d/data
